/**
 * End-to-end: report generated by the Worker's own code, sent by the Worker's
 * own Telegram code. The report text comes from the running local Worker
 * (/preview), so this exercises the real D1 data and the real report builder.
 *
 * Usage: node --experimental-strip-types test/send-report-live.ts <previewJsonUrl>
 */
import { readFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { dotenv } from "./dotenv-lite.ts";
import { sendTelegram } from "../src/telegram.ts";
import type { Env } from "../src/env.ts";

/** Same portable lookup as telegram-live.ts; override with KHMER24_ENV. */
const here = dirname(fileURLToPath(import.meta.url));
const candidates = [
  process.env.KHMER24_ENV,
  resolve(here, "..", "..", ".env"),
  resolve(here, "..", ".env"),
].filter((p): p is string => Boolean(p));
const dotenvPath = candidates.find((p) => existsSync(p));
if (!dotenvPath) {
  console.error(`No .env found. Looked in:\n${candidates.map((c) => `  ${c}`).join("\n")}`);
  console.error("Copy .env.example to .env, or set KHMER24_ENV to point at one.");
  process.exit(2);
}

const previewUrl = process.argv[2];
if (!previewUrl) {
  console.error("usage: node --experimental-strip-types test/send-report-live.ts <previewJsonUrl>");
  process.exit(2);
}

const values = dotenv(readFileSync(dotenvPath, "utf8"));
const env = {
  DB: null as unknown as D1Database,
  TELEGRAM_BOT_TOKEN: values.TELEGRAM_BOT_TOKEN,
  TELEGRAM_CHAT_ID: values.TELEGRAM_CHAT_ID,
} satisfies Env;

console.log(`fetching report from ${previewUrl}`);
const res = await fetch(previewUrl);
if (!res.ok) {
  console.error(`  FAILED: ${previewUrl} returned ${res.status}`);
  process.exitCode = 1;
  throw new Error("preview fetch failed");
}
const payload = (await res.json()) as { count: number; messages: string[]; lengths: number[] };
console.log(`  messages: ${payload.count}  lengths: ${payload.lengths.join(", ")}`);

if (payload.count === 0) {
  console.error("  no report was built - nothing to send");
  process.exitCode = 1;
  throw new Error("empty report");
}

let failures = 0;
for (let i = 0; i < payload.messages.length; i++) {
  const text = payload.messages[i]!;
  const withinLimit = text.length <= 4096;
  console.log(`\n--- sending message ${i + 1}/${payload.count} (${text.length} chars, within 4096: ${withinLimit}) ---`);
  if (!withinLimit) {
    console.error("  FAIL: message exceeds the Telegram limit");
    failures++;
    continue;
  }
  const r = await sendTelegram(env, text);
  console.log(`  ${r.ok ? "OK   " : "FAIL "} ${r.detail}`);
  if (!r.ok) failures++;
}

console.log(`\n${"=".repeat(56)}`);
console.log(failures === 0 ? "  full report delivered by the Worker's own code" : `  ${failures} failure(s)`);
// Set exitCode rather than calling process.exit(): exiting synchronously while a
// socket is still closing trips a libuv assertion on Node 24.
process.exitCode = failures === 0 ? 0 : 1;
